config/routes.rb
Rails.application.routes.draw do
  resources :criteria_definitions
  resources :products
  get '/search', to: 'search#index'

  root to: 'search#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/criteria_definition.rb
class CriteriaDefinition < ApplicationRecord
  validates_presence_of :destination

  def references=(value)
    super(split_values(value))
  end

  def categories=(value)
    super(split_values(value))
  end

  def self.matches_any_reference(reference)
    where("'#{reference}' = ANY (\"references\")")
  end

  def self.contains_any_category(category)
    where('categories && ?', "{#{category}}")
  end

  def self.less_than_price(price)
    no_price_cap.or(self.where("maximum_price >= ?", price))
  end

  def self.no_price_cap
    where("maximum_price IS NULL")
  end

  private

  def split_values(value)
    value.split(',').map(&:strip) unless value.blank?
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :reference, :name, :category, :price, presence: true
  validates :reference, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/criteria_definitions_controller.rb
class CriteriaDefinitionsController < ApplicationController
  before_action :set_criteria_definition, only: %i[ show edit update destroy ]

  # GET /criteria_definitions or /criteria_definitions.json
  def index
    @criteria_definitions = CriteriaDefinition.all
  end

  # GET /criteria_definitions/1 or /criteria_definitions/1.json
  def show
  end

  # GET /criteria_definitions/new
  def new
    @criteria_definition = helpers.decorate(CriteriaDefinition.new)
  end

  # GET /criteria_definitions/1/edit
  def edit
  end

  # POST /criteria_definitions or /criteria_definitions.json
  def create
    @criteria_definition = CriteriaDefinition.new(criteria_definition_params)

    respond_to do |format|
      if @criteria_definition.save
        format.html { redirect_to @criteria_definition, notice: "Criteria definition was successfully created." }
        format.json { render :show, status: :created, location: @criteria_definition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @criteria_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criteria_definitions/1 or /criteria_definitions/1.json
  def update
    respond_to do |format|
      if @criteria_definition.update(criteria_definition_params)
        format.html { redirect_to @criteria_definition, notice: "Criteria definition was successfully updated." }
        format.json { render :show, status: :ok, location: @criteria_definition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @criteria_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criteria_definitions/1 or /criteria_definitions/1.json
  def destroy
    @criteria_definition.destroy
    respond_to do |format|
      format.html { redirect_to criteria_definitions_url, notice: "Criteria definition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criteria_definition
      @criteria_definition = helpers.decorate(CriteriaDefinition.find(params[:id]))
    end

    # Only allow a list of trusted parameters through.
    def criteria_definition_params
      params.require(:criteria_definition).permit(:references, :categories, :maximum_price, :destination)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:reference, :name, :category, :price)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # GET /search
  def index
    @search = SearchService.call(search_params)

    flash.now[:notice] = @search.message if @search.failure?
  end

  private

  def search_params
    params.permit(:product_reference)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def decorate(model, decorate_class = nil)
    (decorate_class || "#{model.class}Decorator".constantize).new(model)
   end
end

app/views/criteria_definitions/_form.html.erb
<%= form_with(model: criteria_definition, html: { class: 'needs-validation' }) do |form| %>
  <div class="row g-3">
    <% if criteria_definition.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(criteria_definition.errors.count, "error") %> prohibited this criteria_definition from being saved:</h2>

        <ul>
          <% criteria_definition.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-sm-12">
      <%= form.label :destination %>
      <%= form.text_field :destination, required: true, class: 'form-control' %>
    </div>

    <div class="col-sm-12">
      <%= form.label :references %>
      <%= form.text_field :references, value: criteria_definition.print_references, class: 'form-control' %>
      <small class="fw-lighter">Assign multiple references by separating entries in comma, e.g. `REF1, REF2`</small>
    </div>

    <div class="col-sm-12">
      <%= form.label :categories %>
      <%= form.text_field :categories, value: criteria_definition.print_categories, class: 'form-control' %>
      <small class="fw-lighter">Assign multiple categories by separating entries in comma, e.g. `console, handheld`</small>
    </div>

    <div class="col-sm-12">
      <%= form.label :maximum_price %>
      <%= form.text_field :maximum_price, class: 'form-control' %>
      <small class="fw-lighter">When left empty, it imposes no price limit during matching.</small>
    </div>

    <div class="col-sm-12">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', criteria_definitions_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/criteria_definitions/edit.html.erb
<div class="row g-5">
  <div class="col-md-8">
    <h4 class="mb-3">Editing Criteria Definition</h4>
    <%= render 'form', criteria_definition: @criteria_definition %>
  </div>
</div>

app/views/criteria_definitions/index.html.erb
<div class="row g-5">
  <div class="col-md-12">
    <h4 class="mb-3">Criteria Definitions</h4>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>References</th>
          <th>Categories</th>
          <th>Maximum price</th>
          <th>Destination</th>
          <th style="text-align: right">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @criteria_definitions.each do |criteria_definition| %>
        <% criteria_decorator = decorate(criteria_definition) %>
          <tr>
            <td><%= criteria_decorator.references_badge %></td>
            <td><%= criteria_decorator.categories_badge %></td>
            <td><%= criteria_decorator.maximum_price %></td>
            <td><%= criteria_decorator.destination %></td>
            <td style="text-align: right">
              <%= link_to 'Show', criteria_decorator %> |
              <%= link_to 'Edit', edit_criteria_definition_path(criteria_decorator) %> |
              <%= link_to 'Destroy', criteria_decorator, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Criteria Definition', new_criteria_definition_path, class: 'btn btn-primary' %>

app/views/criteria_definitions/new.html.erb
<div class="row g-5">
  <div class="col-md-8">
    <h4 class="mb-3">New Criteria Definition</h4>
    <%= render 'form', criteria_definition: @criteria_definition %>
  </div>
</div>

app/views/criteria_definitions/show.html.erb
<table class="table table-bordered">
  <tbody>
  <tr>
    <td><strong>References:</strong></td>
    <td><%= @criteria_definition.references_badge %></td>
  </tr>
  <tr>
    <td><strong>Categories:</strong></td>
    <td><%= @criteria_definition.categories_badge %></td>
  </tr>
  <tr>
    <td><strong>Maximum price:</strong></td>
    <td><%= @criteria_definition.maximum_price %></td>
  </tr>
  <tr>
    <td><strong>Destination:</strong></td>
    <td><%= @criteria_definition.destination %></td>
  </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_criteria_definition_path(@criteria_definition), class: 'btn btn-primary' %>
<%= link_to 'Back', criteria_definitions_path, class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuybayExam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <div class="col-lg-9 mx-auto p-3 py-md-5">
      <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
          <%= link_to "BuyBay", root_path %>

          <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <%= link_to "Product Destination Finder", search_path, class: 'me-4 py-2 text-dark text-decoration-none' %>
            <%= link_to "Products", products_path, class: 'me-4 py-2 text-dark text-decoration-none' %>
            <%= link_to "Criteria Definitions", criteria_definitions_path, class: 'me-4 py-2 text-dark text-decoration-none' %>
          </nav>
        </div>
      </header>

      <main>
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: 'alert alert-info') %>
        <% end %>

        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, html: { class: 'needs-validation' }) do |form| %>
  <div class="row g-3">
    <% if product.errors.any? %>
      <div id="error_explanation" class="col-sm-12">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-sm-12">
      <%= form.label :reference %>
      <%= form.text_field :reference, required: true, class: 'form-control' %>
    </div>

    <div class="col-sm-12">
      <%= form.label :name %>
      <%= form.text_field :name, required: true, class: 'form-control' %>
    </div>

    <div class="col-sm-12">
      <%= form.label :category %>
      <%= form.text_field :category, required: true, class: 'form-control' %>
      <small class="fw-lighter">
        Optional: assign multiple categories by separating entries in comma, e.g. `handheld, console`.
        This results in matching multiple criteria definitions, if any.
      </small>
    </div>

    <div class="col-sm-12">
      <%= form.label :price %>
      <%= form.text_field :price, required: true, class: 'form-control' %>
    </div>

    <div class="col-sm-12">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', products_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="row g-5">
  <div class="col-md-8">
    <h4 class="mb-3">Editing Product</h4>
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/products/index.html.erb
<div class="row g-5">
  <div class="col-md-12">
    <h4 class="mb-3">Products</h4>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Reference</th>
          <th>Name</th>
          <th>Category</th>
          <th>Price</th>
          <th style="text-align: right">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.reference %></td>
            <td><%= product.name %></td>
            <td><%= product.category %></td>
            <td><%= product.price %></td>
            <td style="text-align: right">
              <%= link_to 'Show', product %> |
              <%= link_to 'Edit', edit_product_path(product) %> |
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Product', new_product_path, class: 'btn btn-primary' %>

app/views/products/new.html.erb
<div class="row g-5">
  <div class="col-md-8">
    <h4 class="mb-3">New Product</h4>
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/products/show.html.erb
<table class="table table-bordered">
  <tbody>
    <tr>
      <td><strong>Reference:</strong></td>
      <td><%= @product.reference %></td>
    </tr>
    <tr>
      <td><strong>Name:</strong></td>
      <td><%= @product.name %></td>
    </tr>
    <tr>
      <td><strong>Category:</strong></td>
      <td><%= @product.category %></td>
    </tr>
    <tr>
      <td><strong>Price:</strong></td>
      <td><%= @product.price %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary' %>
<%= link_to 'Back', products_path, class: 'btn btn-secondary' %>

app/views/search/index.html.erb
<div class="row g-5">
  <div class="col-md-12">
    <h4 class="mb-3">Product Destination Finder</h4>

    <%= form_with(url: '/search', method: 'get', local: true) do %>
      <label for="product_reference" class="form-label">Product Reference</label>
      <%= text_field_tag(:product_reference, @search.product_reference, required: true) %>

      <%= submit_tag("Search") %>
    <% end %>

    <% if @search[:result].present? %>
      <br>
      <div class="alert alert-success" role="alert">
        Destination: <%= @search[:result].destination %>
      </div>
    <% end %>
  </div>
</div>